<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Оформление заказа");
global $arSettings;
if($arSettings["DISABLE_ORDER"]["VALUE"] != "Y"){
	$APPLICATION->IncludeComponent(
	"bitrix:sale.order.ajax", 
	"sale_order_ajax_vlad", 
	array(
		"COMPONENT_TEMPLATE" => "sale_order_ajax_vlad",
		"PAY_FROM_ACCOUNT" => "Y",
		"ONLY_FULL_PAY_FROM_ACCOUNT" => "N",
		"ALLOW_AUTO_REGISTER" => "Y",
		"ALLOW_APPEND_ORDER" => "Y",
		"SEND_NEW_USER_NOTIFY" => "Y",
		"DELIVERY_NO_AJAX" => "H",
		"SHOW_NOT_CALCULATED_DELIVERIES" => "L",
		"DELIVERY_NO_SESSION" => "Y",
		"TEMPLATE_LOCATION" => "popup",
		"SPOT_LOCATION_BY_GEOIP" => "Y",
		"DELIVERY_TO_PAYSYSTEM" => "d2p",
		"SHOW_VAT_PRICE" => "N",
		"USE_PREPAYMENT" => "N",
		"COMPATIBLE_MODE" => "N",
		"USE_PRELOAD" => "N",
		"ALLOW_USER_PROFILES" => "N",
		"ALLOW_NEW_PROFILE" => "Y",
		"SHOW_ORDER_BUTTON" => "final_step",
		"SHOW_TOTAL_ORDER_BUTTON" => "N",
		"SHOW_PAY_SYSTEM_LIST_NAMES" => "Y",
		"SHOW_PAY_SYSTEM_INFO_NAME" => "Y",
		"SHOW_DELIVERY_LIST_NAMES" => "Y",
		"SHOW_DELIVERY_INFO_NAME" => "Y",
		"SHOW_DELIVERY_PARENT_NAMES" => "Y",
		"SHOW_STORES_IMAGES" => "Y",
		"SKIP_USELESS_BLOCK" => "Y",
		"BASKET_POSITION" => "after",
		"SHOW_BASKET_HEADERS" => "Y",
		"DELIVERY_FADE_EXTRA_SERVICES" => "Y",
		"SHOW_NEAREST_PICKUP" => "Y",
		"DELIVERIES_PER_PAGE" => "20",
		"PAY_SYSTEMS_PER_PAGE" => "20",
		"PICKUPS_PER_PAGE" => "20",
		"SHOW_PICKUP_MAP" => "Y",
		"SHOW_MAP_IN_PROPS" => "Y",
		"PICKUP_MAP_TYPE" => "yandex",
		"SHOW_COUPONS" => "Y",
		"SHOW_COUPONS_BASKET" => "Y",
		"SHOW_COUPONS_DELIVERY" => "N",
		"SHOW_COUPONS_PAY_SYSTEM" => "N",
		"PROPS_FADE_LIST_1" => array(
			0 => "1",
			1 => "2",
			2 => "3",
		),
		"PROPS_FADE_LIST_2" => array(
			0 => "8",
			1 => "12",
			2 => "13",
			3 => "14",
		),
		"USER_CONSENT" => "Y",
		"USER_CONSENT_ID" => "2",
		"USER_CONSENT_IS_CHECKED" => "Y",
		"USER_CONSENT_IS_LOADED" => "N",
		"ACTION_VARIABLE" => "soa-action",
		"PATH_TO_BASKET" => "/personal/cart/",
		"PATH_TO_PERSONAL" => "/personal/orders/",
		"PATH_TO_PAYMENT" => "/personal/orders/payment/",
		"PATH_TO_AUTH" => "/personal/private/",
		"SET_TITLE" => "Y",
		"DISABLE_BASKET_REDIRECT" => "N",
		"EMPTY_BASKET_HINT_PATH" => "/catalog",
		"USE_PHONE_NORMALIZATION" => "N",
		"PRODUCT_COLUMNS_VISIBLE" => array(
			0 => "PREVIEW_PICTURE",
			1 => "DISCOUNT_PRICE_PERCENT_FORMATED",
			2 => "PRICE_FORMATED",
		),
		"ADDITIONAL_PICT_PROP_13" => "MORE_PHOTO",
		"ADDITIONAL_PICT_PROP_14" => "MORE_PHOTO",
		"BASKET_IMAGES_SCALING" => "adaptive",
		"SERVICES_IMAGES_SCALING" => "adaptive",
		"PRODUCT_COLUMNS_HIDDEN" => array(
		),
		"USE_YM_GOALS" => "N",
		"USE_ENHANCED_ECOMMERCE" => "N",
		"USE_CUSTOM_MAIN_MESSAGES" => "N",
		"USE_CUSTOM_ADDITIONAL_MESSAGES" => "N",
		"USE_CUSTOM_ERROR_MESSAGES" => "N",
		"SHOW_MAP_FOR_DELIVERIES" => array(
			0 => "1",
		),
		"PROPS_FADE_LIST_3" => array(
		),
		"PROPS_FADE_LIST_4" => "",
		"ADDITIONAL_PICT_PROP_23" => "-",
		"ADDITIONAL_PICT_PROP_25" => "-",
		"ADDITIONAL_PICT_PROP_26" => "-",
		"ADDITIONAL_PICT_PROP_34" => "-",
		"ADDITIONAL_PICT_PROP_62" => "-",
		"ADDITIONAL_PICT_PROP_63" => "-",
		"ADDITIONAL_PICT_PROP_71" => "-",
		"HIDE_ORDER_DESCRIPTION" => "N",
		"ADDITIONAL_PICT_PROP_73" => "-",
		"ADDITIONAL_PICT_PROP_74" => "-",
		"ADDITIONAL_PICT_PROP_78" => "-",
		"ADDITIONAL_PICT_PROP_80" => "-",
		"ADDITIONAL_PICT_PROP_104" => "-",
		"ADDITIONAL_PICT_PROP_105" => "-",
		"ADDITIONAL_PICT_PROP_72" => "-",
		"ADDITIONAL_PICT_PROP_96" => "-",
		"ADDITIONAL_PICT_PROP_97" => "-",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"ADDITIONAL_PICT_PROP_114" => "-",
		"ADDITIONAL_PICT_PROP_113" => "-"
	),
	false
);?>
<?} else {
	LocalRedirect(SITE_DIR."personal/cart/");
}?>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>