<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_before.php");?>
<?$elementId = isset($_GET['element-id']) ? $_GET['element-id'] : '';?>

<?if(!strlen($elementId)){?>
	<div class="block">
		Ошибка - товар не найден
	</div>
	<?exit;?>
<?}?>

<?$APPLICATION->IncludeComponent(
    "bitrix:catalog.element",
    ".default",
    Array(
        "IBLOCK_ID" => CATALOG_IBLOCK,
        "IBLOCK_TYPE" => "catalog",
        "ACTION_VARIABLE" => "action",
        "BACKGROUND_IMAGE" => "-",
        "BASKET_URL" => "/personal/basket.php",
        "BLOG_USE" => "N",
        "BRAND_PROPERTY" => "BRAND_REF",
        "BRAND_PROP_CODE" => array("BRAND_REF", ""),
        "BRAND_USE" => "N",
        "BROWSER_TITLE" => "-",
        "CACHE_GROUPS" => "Y",
        "CACHE_TIME" => "N",// CACHE_TIME,
        "CACHE_TYPE" => "N",//CACHE_TYPE,
        "CHECK_SECTION_ID_VARIABLE" => "N",
        "COMPARE_PATH" => "",
        "COMPATIBLE_MODE" => "Y",
        "CONVERT_CURRENCY" => "Y",
        "CURRENCY_ID" => "RUB",
        "DATA_LAYER_NAME" => "dataLayer",
        "DETAIL_PICTURE_MODE" => array("POPUP", "MAGNIFIER"),
        "DETAIL_URL" => "",
        "DISABLE_INIT_JS_IN_COMPONENT" => "N",
        "DISCOUNT_PERCENT_POSITION" => "bottom-right",
        "DISPLAY_COMPARE" => "N",
        "DISPLAY_NAME" => "Y",
        "DISPLAY_PREVIEW_TEXT_MODE" => "E",
        "ELEMENT_CODE" => "",
        "ELEMENT_ID" => $elementId,
        "FB_USE" => "N",
        "FILE_404" => "",
        "OFFERS_LIMIT" => "0",
        "PARTIAL_PRODUCT_PROPERTIES" => "Y",
		"OFFER_TREE_PROPS" => array(
            0 => "IZGIB_3",
            1 => "DIAMETR_5",
            2 => "DLINA_10",
            3 => "OBYEM_1",
            4 => "KOL_VO",
            5 => "RAZMER",
            6 => "UPAKOVKA",
            7 => "TSVET"
        ),
		"DETAIL_OFFERS_PROPERTY_CODE" => array(
            0 => "VES_1"
        ),
		"DETAIL_MAIN_BLOCK_OFFERS_PROPERTY_CODE" => array(
            0 => "VES_1"
        ),
		"PRICE_CODE" => array(
			0 => "Розница",
			1 => "Партнер",
			2 => "Золотой партнер",
			3 => "Платиновый партнер",
			4 => "Серебрянный партнер",
		),
        "PRICE_VAT_INCLUDE" => "Y",
        "PRICE_VAT_SHOW_VALUE" => "N",
        "PRODUCT_ID_VARIABLE" => "id",
        "PRODUCT_INFO_BLOCK_ORDER" => "sku,props",
        "PRODUCT_PAY_BLOCK_ORDER" => "rating,price,quantityLimit,quantity,buttons",
        "PRODUCT_PROPERTIES" => array("NEWPRODUCT", "SALELEADER", "MATERIAL"),
        "PRODUCT_PROPS_VARIABLE" => "prop",
        "PRODUCT_QUANTITY_VARIABLE" => "",
        "PRODUCT_SUBSCRIPTION" => "Y",
        "PROPERTY_CODE" => [],
        "RELATIVE_QUANTITY_FACTOR" => "5",
        "USE_REVIEW" => "Y",
        "REVIEWS_IBLOCK_ID" => 70,
        "SECTION_CODE" => "",
        "SECTION_CODE_PATH" => "",
        "SECTION_ID" => "",
        "SECTION_ID_VARIABLE" => "SECTION_ID",
        "SECTION_URL" => "",
        "SEF_MODE" => "N",
        "SEF_RULE" => "",
        "SET_BROWSER_TITLE" => "Y",
        "SET_CANONICAL_URL" => "N",
        "SET_LAST_MODIFIED" => "N",
        "SET_META_DESCRIPTION" => "Y",
        "SET_META_KEYWORDS" => "Y",
        "SET_STATUS_404" => "N",
        "SET_TITLE" => "Y",
        "SET_VIEWED_IN_COMPONENT" => "N",
        "SHOW_404" => "N",
        "SHOW_CLOSE_POPUP" => "N",
        "SHOW_DEACTIVATED" => "N",
        "SHOW_DISCOUNT_PERCENT" => "Y",
        "SHOW_MAX_QUANTITY" => "M",
        "SHOW_OLD_PRICE" => "N",
        "SHOW_PRICE_COUNT" => "1",
        "SHOW_SLIDER" => "Y",
        "SLIDER_INTERVAL" => "5000",
        "SLIDER_PROGRESS" => "N",
        "STRICT_SECTION_CHECK" => "N",
        "USE_COMMENTS" => "Y",
        "USE_ELEMENT_COUNTER" => "Y",
        "USE_ENHANCED_ECOMMERCE" => "Y",
        "USE_GIFTS_DETAIL" => "Y",
        "USE_GIFTS_MAIN_PR_SECTION_LIST" => "Y",
        "USE_MAIN_ELEMENT_SECTION" => "N",
        "USE_PRICE_COUNT" => "N",
        "USE_PRODUCT_QUANTITY" => "Y",
        "USE_VOTE_RATING" => "Y",
        "VK_USE" => "N",
        "VOTE_DISPLAY_AS_RATING" => "rating",
        "MENU_CHARACT" => "NEW" //"OLD"
    )
);?>
